server:
  port: 8080

app:
  xxx:
    yyy:
      zzz: nihaoxyz


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-train-db?characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  banner:
    location: classpath:banner/fo
#    image:
#      location: classpath:banner/2.jpg
#      pixelmode: block

#Mybatis
mybatis:
  type.aliases.package: com.cn.pojo
  mapper.locations: classpath:mappers/*.xml

mapper:
  mappers: com.cn.utils.MyMapper
  not-empty: false
  identity: MYSQL

#分页插件助手配置

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true